# Select image from https://hub.docker.com/_/php/
image: php:7.1.16-fpm

before_script:
- bash docker_install.sh > /dev/null
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php composer-setup.php
- php -r "unlink('composer-setup.php');"
- php composer.phar install

stages:
  - test

services:
- postgres:latest

variables:
  # Configure pgsql service (https://hub.docker.com/_/pgsql/)
  POSTGRES_DB: zonny
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  DATABASE_URL: "postgres://postgres:root@postgres/zonny"

# We test PHP7 with PostgreSQL
test:app:
  stage: test
  script:
  # Design the database
  - /builds/baudev/ZONNY_API/vendor/bin/doctrine orm:schema-tool:update --force
  # Update documentation
  - curl https://zonny.me/api/v0.2/doc/swagger_auto_generate_json.php
  # Launch Unit tests
  - phpunit --no-configuration /builds/baudev/ZONNY_API/UnitTest --coverage-text --colors=never --teamcity --testdox
  allow_failure: false
