# Select image from https://hub.docker.com/_/php/
image: php:7.1.16-fpm

before_script:
- bash docker_install.sh > /dev/null
- apt-get install zip unzip
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php composer-setup.php
- php -r "unlink('composer-setup.php');"
- php composer.phar install

stages:
  - test

services:
- mdillon/postgis:latest

variables:
  # Configure pgsql service (https://hub.docker.com/_/pgsql/)
  POSTGRES_DB: zonny
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  DATABASE_URL: "postgres://postgres:@mdillon__postgis/zonny"

# We test PHP7 with PostgreSQL, but we allow it to fail
test:app:
  stage: test
  only:
    - tags
  script:
  # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
  - phpunit --no-configuration /builds/baudev/ZONNY_API/UnitTest --teamcity
  allow_failure: false
