language: php
php:
  - 7.1

services:
  - postgresql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files


before_script:
  - composer install
  - composer require php-coveralls/php-coveralls
  - psql -c 'create database zonny;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - mkdir -p build/logs

script:
  - ./vendor/bin/doctrine orm:schema-tool:update --force
  - phpunit --configuration ./phpunit.xml --testsuite All --teamcity --testdox --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls