<?php

namespace ZONNY\Utils;


class ErrorCode
{


    const PASS_TEXT = -1;
    const UNKNOWN_TYPE = 0;
    const DATABASE = 1;
    const INTERN = 2;
    const NOT_A_FRIEND = 3;
    const UPDATE_LOCATATION = 4;
    const EVENT_CREATION_WITHOUT_FRIEND = 5;
    const NOT_AUTHORIZED_SEE_EVENT = 6;
    const EVENT_DOESNT_EXIST_ANYMORE = 7;
    const EVENT_MODIFICATION_FAIL = 8;
    const EVENT_NOT_INVITED = 9;
    const EVENT_DELETION_FAIL = 10;
    const EVENT_FETCH_INFO_FAIL = 11;
    const INVALID_KEY_APP = 12;
    const MISSING_KEY_APP = 13;
    const INVALID_FB_ACCESS_TOKEN = 14;
    const INVALID_FB_ACCESS_TOKEN_EXPIRATION = 15;
    const INVALID_DATETIME = 16;
    const GCM_INVALID_FORMAT = 17;
    const INVALID_AUTH_VARIABLE = 18;
    const INVALID_FRIEND_ID = 19;
    const INVALID_GPS_LOCATION = 20;
    const UNAVAILABLE_MAX_24H = 21;
    const INVALID_PUBLIC_VARIABLE = 22;
    const INVALID_INFORMATIONS_CHARAC = 23;
    const INVALID_URL = 24;
    const GPS_LOCATION_MISSING = 25;
    const EVENT_START_NEXT_24H = 26;
    const EVENT_DURATION_24H_MAX = 27;
    const EVENT_DURATION_LESS_1MINUTE = 28;
    const INVALID_EVENT_ID = 29;
    const EVENT_NOT_CREATOR = 30;
    const EVENT_HAS_ENDED = 31;
    const INVALID_RESPONSE_FORMAT = 32;
    const INVALID_VARIABLE_FORMAT = 33;
    const USER_UNAVAILABLE_CANT_SEE_MAP = 34;
    const USER_MUST_GIVE_POSITION_TO_SEE_MAP = 35;
    const FACEBOOK_SDK_ERROR = 36;
    const MISSING_PARAMTERS = 37;
    const EVENT_IMPOSSIBLE_OPERATION = 38;
    const EVENT_REQUEST_NOT_FOUND = 39;
    const EVENT_REQUEST_ALREADY_INVITED = 40;
    const EVENT_REQUEST_ALREADY_SENT = 41;
    const EVENT_REQUEST_CANT_BE_DELETED = 42;
    const UPDATE_NEEDED = 43;
    

}